### ISSUE TITLE
Reduce pictrs-safety poller logs

### ISSUE THREAD

**Issue by MrKaplan-lw** [db0/lemmy-safety#17]
I might be missing something, but I can't find a way to disable the log message `fedi_safety.pictrs_safety:pop_and_check:35 - nothing to do` that is created every 0.1 seconds without modifying the python code.

As this logs nearly 864k messages a day it would be great to limit this e.g. by being able to adjust the log level via env var.

**Comment by db0** [comment]
Sure that shouldn't be too hard.

**Comment by db0** [comment]
Can you check if setting `LOGURU_LEVEL='INFO'` works?

**Comment by poVoq** [comment]
Would be probably good to add that to the env.example

**Comment by db0** [comment]
Sure, I'll add it when I get the chance or feel free to send a quick PR
